airflow-scheduler-1  | Unable to load the config, contains a configuration error.
airflow-scheduler-1  | Traceback (most recent call last):
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 573, in configure
airflow-scheduler-1  |     handler = self.configure_handler(handlers[name])
airflow-scheduler-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 757, in configure_handler
airflow-scheduler-1  |     result = factory(**kwargs)
airflow-scheduler-1  |              ^^^^^^^^^^^^^^^^^
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/utils/log/file_processor_handler.py", line 50, in __init__
airflow-scheduler-1  |     Path(self._get_log_directory()).mkdir(parents=True, exist_ok=True)
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/pathlib.py", line 1116, in mkdir
airflow-scheduler-1  |     os.mkdir(self, mode)
airflow-scheduler-1  | PermissionError: [Errno 13] Permission denied: '/opt/airflow/logs/scheduler/2025-02-27'
airflow-scheduler-1  | 
airflow-scheduler-1  | The above exception was the direct cause of the following exception:
airflow-scheduler-1  | 
airflow-scheduler-1  | Traceback (most recent call last):
airflow-scheduler-1  |   File "/usr/local/bin/airflow", line 5, in <module>
airflow-scheduler-1  |     from airflow.__main__ import main
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/__init__.py", line 68, in <module>
airflow-scheduler-1  |     settings.initialize()
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/settings.py", line 541, in initialize
airflow-scheduler-1  |     LOGGING_CLASS_PATH = configure_logging()
airflow-scheduler-1  |                          ^^^^^^^^^^^^^^^^^^^
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/logging_config.py", line 74, in configure_logging
airflow-scheduler-1  |     raise e
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/logging_config.py", line 69, in configure_logging
airflow-scheduler-1  |     dictConfig(logging_config)
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 823, in dictConfig
airflow-scheduler-1  |     dictConfigClass(config).configure()
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 580, in configure
airflow-scheduler-1  |     raise ValueError('Unable to configure handler '
airflow-scheduler-1  | ValueError: Unable to configure handler 'processor'
airflow-scheduler-1  | Unable to load the config, contains a configuration error.
airflow-scheduler-1  | Traceback (most recent call last):
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 573, in configure
airflow-scheduler-1  |     handler = self.configure_handler(handlers[name])
airflow-scheduler-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 757, in configure_handler
airflow-scheduler-1  |     result = factory(**kwargs)
airflow-scheduler-1  |              ^^^^^^^^^^^^^^^^^
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/utils/log/file_processor_handler.py", line 50, in __init__
airflow-scheduler-1  |     Path(self._get_log_directory()).mkdir(parents=True, exist_ok=True)
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/pathlib.py", line 1116, in mkdir
airflow-scheduler-1  |     os.mkdir(self, mode)
airflow-scheduler-1  | PermissionError: [Errno 13] Permission denied: '/opt/airflow/logs/scheduler/2025-02-27'
airflow-scheduler-1  | 
airflow-scheduler-1  | The above exception was the direct cause of the following exception:
airflow-scheduler-1  | 
airflow-scheduler-1  | Traceback (most recent call last):
airflow-scheduler-1  |   File "/usr/local/bin/airflow", line 5, in <module>
airflow-scheduler-1  |     from airflow.__main__ import main
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/__init__.py", line 68, in <module>
airflow-scheduler-1  |     settings.initialize()
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/settings.py", line 541, in initialize
airflow-scheduler-1  |     LOGGING_CLASS_PATH = configure_logging()
airflow-scheduler-1  |                          ^^^^^^^^^^^^^^^^^^^
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/logging_config.py", line 74, in configure_logging
airflow-scheduler-1  |     raise e
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/logging_config.py", line 69, in configure_logging
airflow-scheduler-1  |     dictConfig(logging_config)
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 823, in dictConfig
airflow-scheduler-1  |     dictConfigClass(config).configure()
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 580, in configure
airflow-scheduler-1  |     raise ValueError('Unable to configure handler '
airflow-scheduler-1  | ValueError: Unable to configure handler 'processor'
airflow-scheduler-1  | Unable to load the config, contains a configuration error.
airflow-scheduler-1  | Traceback (most recent call last):
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 573, in configure
airflow-scheduler-1  |     handler = self.configure_handler(handlers[name])
airflow-scheduler-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 757, in configure_handler
airflow-scheduler-1  |     result = factory(**kwargs)
airflow-scheduler-1  |              ^^^^^^^^^^^^^^^^^
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/utils/log/file_processor_handler.py", line 50, in __init__
airflow-scheduler-1  |     Path(self._get_log_directory()).mkdir(parents=True, exist_ok=True)
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/pathlib.py", line 1116, in mkdir
airflow-scheduler-1  |     os.mkdir(self, mode)
airflow-scheduler-1  | PermissionError: [Errno 13] Permission denied: '/opt/airflow/logs/scheduler/2025-02-27'
airflow-scheduler-1  | 
airflow-scheduler-1  | The above exception was the direct cause of the following exception:
airflow-scheduler-1  | 
airflow-scheduler-1  | Traceback (most recent call last):
airflow-scheduler-1  |   File "/usr/local/bin/airflow", line 5, in <module>
airflow-scheduler-1  |     from airflow.__main__ import main
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/__init__.py", line 68, in <module>
airflow-scheduler-1  |     settings.initialize()
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/settings.py", line 541, in initialize
airflow-scheduler-1  |     LOGGING_CLASS_PATH = configure_logging()
airflow-scheduler-1  |                          ^^^^^^^^^^^^^^^^^^^
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/logging_config.py", line 74, in configure_logging
airflow-scheduler-1  |     raise e
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/logging_config.py", line 69, in configure_logging
airflow-scheduler-1  |     dictConfig(logging_config)
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 823, in dictConfig
airflow-scheduler-1  |     dictConfigClass(config).configure()
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 580, in configure
airflow-scheduler-1  |     raise ValueError('Unable to configure handler '
airflow-scheduler-1  | ValueError: Unable to configure handler 'processor'
airflow-scheduler-1  | Unable to load the config, contains a configuration error.
airflow-scheduler-1  | Traceback (most recent call last):
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 573, in configure
airflow-scheduler-1  |     handler = self.configure_handler(handlers[name])
airflow-scheduler-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 757, in configure_handler
airflow-scheduler-1  |     result = factory(**kwargs)
airflow-scheduler-1  |              ^^^^^^^^^^^^^^^^^
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/utils/log/file_processor_handler.py", line 50, in __init__
airflow-scheduler-1  |     Path(self._get_log_directory()).mkdir(parents=True, exist_ok=True)
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/pathlib.py", line 1116, in mkdir
airflow-scheduler-1  |     os.mkdir(self, mode)
airflow-scheduler-1  | PermissionError: [Errno 13] Permission denied: '/opt/airflow/logs/scheduler/2025-02-27'
airflow-scheduler-1  | 
airflow-scheduler-1  | The above exception was the direct cause of the following exception:
airflow-scheduler-1  | 
airflow-scheduler-1  | Traceback (most recent call last):
airflow-scheduler-1  |   File "/usr/local/bin/airflow", line 5, in <module>
airflow-scheduler-1  |     from airflow.__main__ import main
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/__init__.py", line 68, in <module>
airflow-scheduler-1  |     settings.initialize()
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/settings.py", line 541, in initialize
airflow-scheduler-1  |     LOGGING_CLASS_PATH = configure_logging()
airflow-scheduler-1  |                          ^^^^^^^^^^^^^^^^^^^
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/logging_config.py", line 74, in configure_logging
airflow-scheduler-1  |     raise e
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/logging_config.py", line 69, in configure_logging
airflow-scheduler-1  |     dictConfig(logging_config)
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 823, in dictConfig
airflow-scheduler-1  |     dictConfigClass(config).configure()
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 580, in configure
airflow-scheduler-1  |     raise ValueError('Unable to configure handler '
airflow-scheduler-1  | ValueError: Unable to configure handler 'processor'
airflow-scheduler-1  | Unable to load the config, contains a configuration error.
airflow-scheduler-1  | Traceback (most recent call last):
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 573, in configure
airflow-scheduler-1  |     handler = self.configure_handler(handlers[name])
airflow-scheduler-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 757, in configure_handler
airflow-scheduler-1  |     result = factory(**kwargs)
airflow-scheduler-1  |              ^^^^^^^^^^^^^^^^^
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/utils/log/file_processor_handler.py", line 50, in __init__
airflow-scheduler-1  |     Path(self._get_log_directory()).mkdir(parents=True, exist_ok=True)
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/pathlib.py", line 1116, in mkdir
airflow-scheduler-1  |     os.mkdir(self, mode)
airflow-scheduler-1  | PermissionError: [Errno 13] Permission denied: '/opt/airflow/logs/scheduler/2025-02-27'
airflow-scheduler-1  | 
airflow-scheduler-1  | The above exception was the direct cause of the following exception:
airflow-scheduler-1  | 
airflow-scheduler-1  | Traceback (most recent call last):
airflow-scheduler-1  |   File "/usr/local/bin/airflow", line 5, in <module>
airflow-scheduler-1  |     from airflow.__main__ import main
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/__init__.py", line 68, in <module>
airflow-scheduler-1  |     settings.initialize()
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/settings.py", line 541, in initialize
airflow-scheduler-1  |     LOGGING_CLASS_PATH = configure_logging()
airflow-scheduler-1  |                          ^^^^^^^^^^^^^^^^^^^
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/logging_config.py", line 74, in configure_logging
airflow-scheduler-1  |     raise e
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/logging_config.py", line 69, in configure_logging
airflow-scheduler-1  |     dictConfig(logging_config)
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 823, in dictConfig
airflow-scheduler-1  |     dictConfigClass(config).configure()
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 580, in configure
airflow-scheduler-1  |     raise ValueError('Unable to configure handler '
airflow-scheduler-1  | ValueError: Unable to configure handler 'processor'
airflow-scheduler-1  | Unable to load the config, contains a configuration error.
airflow-scheduler-1  | Traceback (most recent call last):
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 573, in configure
airflow-scheduler-1  |     handler = self.configure_handler(handlers[name])
airflow-scheduler-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 757, in configure_handler
airflow-scheduler-1  |     result = factory(**kwargs)
airflow-scheduler-1  |              ^^^^^^^^^^^^^^^^^
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/utils/log/file_processor_handler.py", line 50, in __init__
airflow-scheduler-1  |     Path(self._get_log_directory()).mkdir(parents=True, exist_ok=True)
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/pathlib.py", line 1116, in mkdir
airflow-scheduler-1  |     os.mkdir(self, mode)
airflow-scheduler-1  | PermissionError: [Errno 13] Permission denied: '/opt/airflow/logs/scheduler/2025-02-27'
airflow-scheduler-1  | 
airflow-scheduler-1  | The above exception was the direct cause of the following exception:
airflow-scheduler-1  | 
airflow-scheduler-1  | Traceback (most recent call last):
airflow-scheduler-1  |   File "/usr/local/bin/airflow", line 5, in <module>
airflow-scheduler-1  |     from airflow.__main__ import main
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/__init__.py", line 68, in <module>
airflow-scheduler-1  |     settings.initialize()
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/settings.py", line 541, in initialize
airflow-scheduler-1  |     LOGGING_CLASS_PATH = configure_logging()
airflow-scheduler-1  |                          ^^^^^^^^^^^^^^^^^^^
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/logging_config.py", line 74, in configure_logging
airflow-scheduler-1  |     raise e
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/logging_config.py", line 69, in configure_logging
airflow-scheduler-1  |     dictConfig(logging_config)
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 823, in dictConfig
airflow-scheduler-1  |     dictConfigClass(config).configure()
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 580, in configure
airflow-scheduler-1  |     raise ValueError('Unable to configure handler '
airflow-scheduler-1  | ValueError: Unable to configure handler 'processor'
airflow-scheduler-1  | Unable to load the config, contains a configuration error.
airflow-scheduler-1  | Traceback (most recent call last):
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 573, in configure
airflow-scheduler-1  |     handler = self.configure_handler(handlers[name])
airflow-scheduler-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 757, in configure_handler
airflow-scheduler-1  |     result = factory(**kwargs)
airflow-scheduler-1  |              ^^^^^^^^^^^^^^^^^
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/utils/log/file_processor_handler.py", line 50, in __init__
airflow-scheduler-1  |     Path(self._get_log_directory()).mkdir(parents=True, exist_ok=True)
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/pathlib.py", line 1116, in mkdir
airflow-scheduler-1  |     os.mkdir(self, mode)
airflow-scheduler-1  | PermissionError: [Errno 13] Permission denied: '/opt/airflow/logs/scheduler/2025-02-27'
airflow-scheduler-1  | 
airflow-scheduler-1  | The above exception was the direct cause of the following exception:
airflow-scheduler-1  | 
airflow-scheduler-1  | Traceback (most recent call last):
airflow-scheduler-1  |   File "/usr/local/bin/airflow", line 5, in <module>
airflow-scheduler-1  |     from airflow.__main__ import main
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/__init__.py", line 68, in <module>
airflow-scheduler-1  |     settings.initialize()
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/settings.py", line 541, in initialize
airflow-scheduler-1  |     LOGGING_CLASS_PATH = configure_logging()
airflow-scheduler-1  |                          ^^^^^^^^^^^^^^^^^^^
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/logging_config.py", line 74, in configure_logging
airflow-scheduler-1  |     raise e
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/logging_config.py", line 69, in configure_logging
airflow-scheduler-1  |     dictConfig(logging_config)
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 823, in dictConfig
airflow-scheduler-1  |     dictConfigClass(config).configure()
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 580, in configure
airflow-scheduler-1  |     raise ValueError('Unable to configure handler '
airflow-scheduler-1  | ValueError: Unable to configure handler 'processor'
airflow-scheduler-1  | Unable to load the config, contains a configuration error.
airflow-scheduler-1  | Traceback (most recent call last):
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 573, in configure
airflow-scheduler-1  |     handler = self.configure_handler(handlers[name])
airflow-scheduler-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 757, in configure_handler
airflow-scheduler-1  |     result = factory(**kwargs)
airflow-scheduler-1  |              ^^^^^^^^^^^^^^^^^
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/utils/log/file_processor_handler.py", line 50, in __init__
airflow-scheduler-1  |     Path(self._get_log_directory()).mkdir(parents=True, exist_ok=True)
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/pathlib.py", line 1116, in mkdir
airflow-scheduler-1  |     os.mkdir(self, mode)
airflow-scheduler-1  | PermissionError: [Errno 13] Permission denied: '/opt/airflow/logs/scheduler/2025-02-27'
airflow-scheduler-1  | 
airflow-scheduler-1  | The above exception was the direct cause of the following exception:
airflow-scheduler-1  | 
airflow-scheduler-1  | Traceback (most recent call last):
airflow-scheduler-1  |   File "/usr/local/bin/airflow", line 5, in <module>
airflow-scheduler-1  |     from airflow.__main__ import main
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/__init__.py", line 68, in <module>
airflow-scheduler-1  |     settings.initialize()
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/settings.py", line 541, in initialize
airflow-scheduler-1  |     LOGGING_CLASS_PATH = configure_logging()
airflow-scheduler-1  |                          ^^^^^^^^^^^^^^^^^^^
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/logging_config.py", line 74, in configure_logging
airflow-scheduler-1  |     raise e
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/site-packages/airflow/logging_config.py", line 69, in configure_logging
airflow-scheduler-1  |     dictConfig(logging_config)
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 823, in dictConfig
airflow-scheduler-1  |     dictConfigClass(config).configure()
airflow-scheduler-1  |   File "/usr/local/lib/python3.11/logging/config.py", line 580, in configure
airflow-scheduler-1  |     raise ValueError('Unable to configure handler '
airflow-scheduler-1  | ValueError: Unable to configure handler 'processor'
